apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fk68q05pl-go
  janus-idp.io/tekton: fk68q05pl-go
  backstage.io/kubernetes-id: fk68q05pl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fk68q05pl-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
